name: Filter Invalid URLs

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  push:
    branches:
      - main

jobs:
  filter-urls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install aiohttp  # Ensure aiohttp is installed for async requests

    - name: Run filter script
      run: |
        mkdir -p output
        python scripts/filter_valid_urls.py

    - name: Upload filtered JSON and log to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-${{ github.run_id }}
        files: |
          output/filtered_haha.json
          output/invalid_urls.log  # Log of invalid URLs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

