name: Publish filtered plugins

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-filtered-plugins:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run filter script
        run: |
          python main.py

      - name: Upload filtered JSON and log to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.run_id }}
          files: |
            dist/filtered_plugin.json

